# install devtools, reticulate and miniconda
install.packages("devtools", dependencies = TRUE)
install.packages("reticulate", dependencies = TRUE)
reticulate::install_miniconda()
# create conda environment for packages installation
if ("refpop_geno_pred_env" %in% conda_list()$name) {
  use_condaenv("refpop_geno_pred_env")
} else {
  conda_create("refpop_geno_pred_env")
  use_condaenv("refpop_geno_pred_env")
  devtools::install_github("ljacquin/KRMM")
  devtools::install_github("rstudio/tensorflow")
  library(tensorflow)
  install_tensorflow(envname = "refpop_geno_pred_env")
  py_install("umap-learn", pip = T, pip_ignore_installed = T)
  install.packages("umap")
}
# install used packages
install.packages("keras3", dependencies = TRUE)
install.packages("Matrix", dependencies = TRUE)
install.packages("matrixcalc", dependencies = TRUE)
install.packages("data.table", dependencies = TRUE)
install.packages("EMMREML", dependencies = TRUE)
install.packages("BiocManager")
BiocManager::install("impute")
BiocManager::install("snpStats")
install.packages("remotes")
remotes::install_github("hemstrow/snpR")
install.packages("snpReady", dependencies = TRUE)
install.packages("stringr", dependencies = TRUE)
install.packages("FactoMineR", dependencies = TRUE)
install.packages("rstudioapi", dependencies = TRUE)
install.packages("doParallel", dependencies = TRUE)
install.packages("doRNG", dependencies = TRUE)
install.packages("robustbase", dependencies = TRUE)
install.packages("foreach", dependencies = TRUE)
install.packages("parallel", dependencies = TRUE)
install.packages("missForest", dependencies = TRUE)
install.packages("rgl", dependencies = TRUE)
install.packages("cvTools", dependencies = TRUE)
install.packages("ggplot2", dependencies = TRUE)
install.packages("plotly", dependencies = TRUE)
install.packages("htmlwidgets", dependencies = TRUE)
install.packages("dplyr", dependencies = TRUE)
install.packages("kernlab", dependencies = TRUE)
install.packages("glmnet", dependencies = TRUE)
install.packages("ranger", dependencies = TRUE)
install.packages("tidyverse", dependencies = TRUE)
install.packages("tidyr", dependencies = TRUE)
install.packages("lubridate", dependencies = TRUE)
install.packages("emmeans", dependencies = TRUE)
install.packages("lsmeans", dependencies = TRUE)
install.packages("SpATS", dependencies = TRUE)
install.packages("lme4", dependencies = TRUE)
install.packages("anytime", dependencies = TRUE)
install.packages("bigsnpr", dependencies = TRUE)
